// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Linq.Expression.Optimizer.net35")>]
[<assembly: AssemblyProductAttribute("Linq.Expression.Optimizer")>]
[<assembly: AssemblyDescriptionAttribute("Lightweight optimizer of System.Linq.Expression expressions. Just basic boolean algebra and reductions, constant and tuple/anonymous type eliminations.")>]
[<assembly: AssemblyVersionAttribute("1.0.14")>]
[<assembly: AssemblyFileVersionAttribute("1.0.14")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Linq.Expression.Optimizer.net35"
    let [<Literal>] AssemblyProduct = "Linq.Expression.Optimizer"
    let [<Literal>] AssemblyDescription = "Lightweight optimizer of System.Linq.Expression expressions. Just basic boolean algebra and reductions, constant and tuple/anonymous type eliminations."
    let [<Literal>] AssemblyVersion = "1.0.14"
    let [<Literal>] AssemblyFileVersion = "1.0.14"
