name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
body:
  - type: textarea
    id: feature-info
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Add any screenshots about the feature request here.
      value: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: expected-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      render: shell
  - type: textarea
    id: alternatives-info
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      render: shell
  - type: textarea
    id: additional-ctx
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      render: shell
